// <auto-generated />
using System;
using GamesRental.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesRental.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230130172507_employee")]
    partial class employee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GamesRental.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GamesRental.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "425 532 841",
                            DateOfBirth = new DateTime(1985, 3, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.green@gmail.com",
                            FirstName = "James",
                            LastName = "Green"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "421 298 915",
                            DateOfBirth = new DateTime(1994, 3, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tom.davies@gmail.com",
                            FirstName = "Tom",
                            LastName = "Davies"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "924 941 012",
                            DateOfBirth = new DateTime(1975, 9, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bush@gmail.com",
                            FirstName = "Jean",
                            LastName = "Bush"
                        });
                });

            modelBuilder.Entity("GamesRental.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Elder Scrolls V: Skyrim is an action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks. It is the fifth main installment in The Elder Scrolls series, following 2006's The Elder Scrolls IV: Oblivion, and was released worldwide for Microsoft Windows, PlayStation 3, and Xbox 360 on November 11, 2011.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756169/iol0eltwhjl2e4t0ru2j.jpg",
                            Price = 6.99m,
                            Title = "Skyrim"
                        },
                        new
                        {
                            Id = 2,
                            Description = "FIFA 23 is a football video game published by Electronic Arts. It is the 30th installment in the FIFA series that is developed by EA Sports, and the final installment under the FIFA banner, and released worldwide on 30 September 2022 for PC, Nintendo Switch, PlayStation 4, PlayStation 5, Xbox One and Xbox Series X/S.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674755549/ha1q3ipzh1xcdzkanqwf.jpg",
                            Price = 68.00m,
                            Title = "Fifa 23"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Elden Ring is an action role-playing game played in a third person perspective, with gameplay focusing on combat and exploration. It features elements similar to those found in other games developed by FromSoftware, such as the Dark Souls series, Bloodborne, and Sekiro: Shadows Die Twice.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674755962/baxtap8rqrscyror5i9t.jpg",
                            Price = 48.00m,
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Minecraft is a video game in which players create and break apart various kinds of blocks in three-dimensional worlds. The game's two main modes are Survival and Creative. In Survival, players must find their own building supplies and food.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756102/femn6kdwsbnp9hjirbwh.jpg",
                            Price = 9.99m,
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 5,
                            Description = "In God of War, players control Kratos, a Spartan warrior who is sent by the Greek gods to kill Ares, the god of war. As the story progresses, Kratos is revealed to be Ares' former servant, who had been tricked into killing his own family and is haunted by terrible nightmares.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756274/nosaemw1eb8gockduumq.jpg",
                            Price = 40.00m,
                            Title = "God of war"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Immortality is the indefinite continuation of a person's existence, even after death. In common parlance, immortality is virtually indistinguishable from afterlife, but philosophically speaking, they are not identical.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756385/yniwzfje8mc5xwudfhjo.jpg",
                            Price = 19.99m,
                            Title = "Immortality"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Lost, alone and separated from family, a stray cat must untangle an ancient mystery to escape a long-forgotten city. Stray is a third-person cat adventure game set amidst the detailed, neon-lit alleys of a decaying cybercity and the murky environments of its seedy underbelly.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756441/mizrusvx8omejavlccua.jpg",
                            Price = 29.99m,
                            Title = "Stray"
                        },
                        new
                        {
                            Id = 38,
                            Description = "NORCO is a Southern Gothic point & click narrative adventure that immerses the player in the sinking suburbs and verdant industrial swamps of a distorted South Louisiana. Your brother Blake has gone missing in the aftermath of your mother's death.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756474/eqnullat0nnnuignobfr.jpg",
                            Price = 18.00m,
                            Title = "Norco"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Stranded in a ruined land, and armed with only your own curiosity, you will confront colossal beasts, collect strange and powerful items, and unravel long-lost secrets. Stories say that a great treasure is hidden somewhere in this land.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756549/psjlu6es1gqdlci6ujqa.jpg",
                            Price = 29.99m,
                            Title = "Tunic"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Cult of the Lamb casts players in the role of a possessed lamb saved from annihilation by an ominous stranger and must repay their debt by building a loyal following in his name.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756589/tf7tonfsxdjcu1yqonhg.jpg",
                            Price = 29.98m,
                            Title = "Cult of the Lamb"
                        },
                        new
                        {
                            Id = 41,
                            Description = "The player assumes a detective role in connecting together the details of the narrative from eleven cases, placing the player at or shortly after a static point in time where a central character in the narrative has met their death.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756675/c7xcodbhrxl6wlzp6tjq.jpg",
                            Price = 12.74m,
                            Title = "The Case of the Golden Idol"
                        },
                        new
                        {
                            Id = 42,
                            Description = "It was announced in December 2017, and was released on October 28, 2022. The game follows the titular angel-hunting witch Bayonetta, who must face against man-made bioweapons called Homunculi, and an entity known as the Singularity which threatens to destroy the multiverse.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756728/a7n10bqmpryi0leup2t6.jpg",
                            Price = 49.95m,
                            Title = "Bayonetta 3"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Total War is a series of strategy games developed by British developer Creative Assembly for personal computers. They combine turn-based strategy and resource management with real-time tactical control of battles.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756765/al8cjf9tfly9izjsp05h.jpg",
                            Price = 59.99m,
                            Title = "Total War: Warhammer III"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Splatoon is a third-person shooter developed and published by Nintendo. The game features battles between Inklings, using weaponized ink to cover territory and \"splat\" opponents. The game was first revealed at the Nintendo E3 2014 Digital Event and was released for the Wii U on 29 May 2015.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756884/lexygrrjh1git6qxl76q.jpg",
                            Price = 39.99m,
                            Title = "Splatoon 3"
                        },
                        new
                        {
                            Id = 45,
                            Description = "In the story of Neon White, Heaven deals with a demon infestation, and a group of assassins called Neons are getting a chance to stay in Heaven by competing against each other in dealing with the demon threat.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674756937/hm4h0tw3plhkkmtklvtw.jpg",
                            Price = 24.99m,
                            Title = "Neon White"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Pentiment is a narrative adventure role-playing video game set in Bavaria in the 16th century.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674757083/hlmdovah56su3ye8yfdy.jpg",
                            Price = 19.99m,
                            Title = "Pentiment"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Horizon Forbidden West is a 2022 action role-playing game developed by Guerrilla Games and published by Sony Interactive Entertainment. The sequel to 2017's Horizon Zero Dawn, the game is set in a post-apocalyptic version of the Western United States recovering from the aftermath of an extinction event caused by a rogue robot swarm.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674757067/vel3aepnxv5pwqldqgw5.jpg",
                            Price = 70.00m,
                            Title = "Horizon Forbidden West"
                        },
                        new
                        {
                            Id = 48,
                            Description = "OlliOlli World is a sports video game developed by Roll7 and published by Private Division. As the third game in the OlliOlli series, the game was released for Microsoft Windows, Nintendo Switch, PlayStation 4, PlayStation 5, Xbox One, and Xbox Series X/S in February 2022.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674757145/r5knzzhs4mgtmckqjbwd.jpg",
                            Price = 29.99m,
                            Title = "OlliOlli World"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Return to Monkey Island is a point-and-click adventure game developed by Terrible Toybox and published by Devolver Digital. The sixth Monkey Island game, it was released for macOS, Nintendo Switch, and Windows on September 19, 2022.",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674757192/jkzyzvvytllnzferyrgu.jpg",
                            Price = 26.00m,
                            Title = "Return to Monkey Island"
                        },
                        new
                        {
                            Id = 50,
                            Description = "A Little To The Left is something like a non-traditional point-and-click. Players don't move through the world, but instead, interact by just dragging and dropping objects around the screen",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674757249/clackjfg16kzplzxgbvj.jpg",
                            Price = 13.55m,
                            Title = "A Little to the Left"
                        },
                        new
                        {
                            Id = 51,
                            Description = "The final component of the gameplay worth mentioning is the Snap mechanic: At any point during the match, players can “snap” to increase the Cosmic Cubes (rank trophies) that they will win or lose in the match",
                            Image = "http://res.cloudinary.com/dbtbooroa/image/upload/v1674757318/kcpvggh63ffvpi8ym8io.jpg",
                            Price = 0.01m,
                            Title = "Marvel Snap"
                        });
                });

            modelBuilder.Entity("GamesRental.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("PriceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GamesRental.Models.Order", b =>
                {
                    b.HasOne("GamesRental.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
